#! /bin/sh
echo 10 > /proc/sys/vm/dirty_ratio
echo 8 > /proc/sys/vm/dirty_background_ratio

mount -o remount,size=20m /tmp

mkdir -p /etc/samba
chmod 0710 /opt/ipnc/etc/esmtprc
cp /opt/ipnc/quftprc /etc/quftprc
cp /opt/ipnc/ushare.conf /mnt/data
cp /opt/ipnc/etc/ushare.conf /etc
cp /opt/ipnc/etc/boa.conf /etc
cp /opt/ipnc/etc/smb.conf /etc/samba
cp /opt/ipnc/etc/esmtprc /etc
cp /opt/ipnc/etc/ppp/* /etc/ppp
cd /opt/ipnc
cp testmail.txt /etc/
/opt/ipnc/loadmodules.sh
/opt/ipnc/watchdog &
