############################################################
# File: Makefile
#
############################################################
ROOTDIR = ../../..
include $(ROOTDIR)/Rules.make

INSTALLDIR = $(EXEC_DIR)

BIN  = wshaper

install:
	cp -f $(BIN) $(INSTALLDIR)

uninstall:
	rm -rf $(INSTALLDIR)/$(BIN)

clean:
	
